import { Roboto } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ['400', '500'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="billy_scrollbar">
      <body className={roboto.className}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
